# Sample workflow for building and deploying a Hugo site to GitHub Pages
name = "Deploy Hugo site to Pages"

[on]
  [on.push]
    branches = ["main"]
  [on.workflow_dispatch]

[permissions]
  contents = "read"
  pages = "write"
  id-token = "write"

[concurrency]
  group = "pages"
  cancel-in-progress = false

[defaults.run]
  shell = "bash"

[jobs.build]
  runs-on = "ubuntu-latest"
  [jobs.build.env]
    HUGO_VERSION = "0.121.1"
  [[jobs.build.steps]]
    name = "Install Hugo CLI"
    run = """
    wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb &&
    sudo dpkg -i ${{ runner.temp }}/hugo.deb
    """
  [[jobs.build.steps]]
    name = "Install Dart Sass"
    run = "sudo snap install dart-sass"
  [[jobs.build.steps]]
    name = "Checkout"
    uses = "actions/checkout@v4"
    [jobs.build.steps.with]
      submodules = "recursive"
      fetch-depth = 0
  [[jobs.build.steps]]
    name = "Setup Pages"
    id = "pages"
    uses = "actions/configure-pages@v4"
  [[jobs.build.steps]]
    name = "Install Node.js dependencies"
    run = "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
  [[jobs.build.steps]]
    name = "Build with Hugo"
    [jobs.build.steps.env]
      HUGO_ENVIRONMENT = "production"
      HUGO_ENV = "production"
    run = """
    hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
    """
  [[jobs.build.steps]]
    name = "Upload artifact"
    uses = "actions/upload-pages-artifact@v3"
    [jobs.build.steps.with]
      path = "./public"

[jobs.deploy]
  [jobs.deploy.environment]
    name = "github-pages"
    url = "${{ steps.deployment.outputs.page_url }}"
  runs-on = "ubuntu-latest"
  needs = ["build"]
  [[jobs.deploy.steps]]
    name = "Deploy to GitHub Pages"
    id = "deployment"
    uses = "actions/deploy-pages@v4"

